name: build
on:
  push: 

jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: build
        run: |
          yarn
